import { useEffect, useRef, useState } from 'react'
import { FiArrowRight, FiArrowUpRight, FiCheck, FiGithub, FiSearch, FiX } from 'react-icons/fi'

const projects = [
  { id: 'trialsage', number: '01', category: 'APPLIED AI / HYBRID RAG', name: 'TrialSage', subtitle: 'A smarter path to the right clinical trial.', description: 'Making complex clinical-trial data searchable with an AI-powered system that connects structured queries, semantic search, and grounded answers.', tech: ['Python', 'PostgreSQL', 'pgvector', 'Llama 3.1'], metric: '39K+', metricLabel: 'clinical trials indexed', url: 'https://github.com/tanyamistry/TrialSage', details: ['Searches 39K+ clinical trials and 966K+ eligibility criteria using a hybrid of text-to-SQL and semantic vector search.', 'Routes queries with confidence scoring and a rule-based fallback, matching the retrieval approach to the question.', 'Uses polarity-aware NLP to distinguish inclusion from exclusion criteria; identified and corrected 1,455 mislabeled criteria.', 'Includes citation guardrails, 200+ automated tests, and latency and token tracing.'] },
  { id: 'stream', number: '02', category: 'DATA ENGINEERING / STREAMING', name: 'Market in motion.', subtitle: 'Live trades. Reliable pipelines. Clear signals.', description: 'A real-time crypto market pipeline that turns a constant stream of Coinbase trades into accurate, time-windowed market analytics.', tech: ['Kafka', 'Spark', 'PostgreSQL', 'Docker'], metric: '10K+', metricLabel: 'events processed / minute', url: 'https://github.com/tanyamistry/streaming-market-pipeline', details: ['Ingests live trades from the Coinbase WebSocket and processes 10K+ events per minute with Kafka and Spark Structured Streaming.', 'Builds OHLCV candles with watermarking for accurate time-windowed analytics, storing raw trades and one-minute candles in PostgreSQL.', 'Serves an auto-refreshing Streamlit dashboard with Plotly candlestick charts.', 'Packages the complete stack in Docker Compose for reproducible deployment.'] },
  { id: 'charts', number: '03', category: 'COMPUTER VISION / LOCAL AI', name: 'Beyond the chart.', subtitle: 'From pixels to “oh, that’s interesting.”', description: 'A local AI workflow that reads chart images and turns them into plain-English findings, trends, and anomalies.', tech: ['OpenCV', 'EasyOCR', 'LLaVA', 'Streamlit'], metric: '4', metricLabel: 'ways to understand your data', url: 'https://github.com/tanyamistry/automated-chart-insights-generator', details: ['Extracts chart structure, axis labels, and data points with OpenCV and EasyOCR.', 'Passes structured metadata to a local LLaVA vision model through Ollama for plain-English interpretation across multiple chart types.', 'Organizes the result into four sections: summary, findings, trends, and anomalies.', 'Provides an interactive Streamlit interface and JSON export for further analysis.'] },
]

function WindowBar({ title }: { title: string }) { return <div className="window-bar"><span className="window-dots"><i /><i /><i /></span><span>{title}</span><span>↗</span></div> }

function ProjectVisual({ id }: { id: string }) {
  if (id === 'trialsage') return <div className="project-art trialsage-art" aria-hidden="true"><span className="art-orbit" /><div className="mock-window trial-window"><WindowBar title="trialsage / intelligent discovery" /><div className="trial-body"><span className="trial-logo">✳ <strong>TrialSage</strong></span><p>A better match starts<br />with a better question.</p><div className="trial-search"><FiSearch /><span>Find the right clinical trial...</span><span className="search-arrow"><FiArrowRight /></span></div><div className="trial-result"><span className="result-icon"><FiCheck /></span><div><strong>Connected. Contextual. Cited.</strong><span>Hybrid retrieval · Grounded responses</span></div><span className="result-badge">RAG</span></div><div className="trial-bottom"><span>39K+ trials</span><span>966K+ criteria</span><span>One smarter search.</span></div></div></div><span className="visual-note">less searching. more finding. <span>↗</span></span></div>
  if (id === 'stream') return <div className="project-art stream-art" aria-hidden="true"><div className="mock-window market-window"><WindowBar title="market.stream / pipeline preview" /><div className="market-body"><div className="market-top"><span>BTC / USD <small>COINBASE</small></span><span className="market-live"><i /> STREAMING</span></div><div className="market-headline"><strong>Signal from the noise.</strong><span>1 MINUTE CANDLES</span></div><div className="candlestick-chart">{Array.from({ length: 24 }, (_, i) => { const up = [0, 1, 4, 5, 7, 10, 12, 13, 15, 16, 18, 19, 21, 23].includes(i); return <div className={`candle ${up ? 'up' : 'down'}`} key={i} style={{ height: `${28 + (i * 17 % 49)}px`, bottom: `${14 + i * 3.4 + Math.sin(i) * 21}px` }}><i /></div> })}</div><div className="pipeline-mini"><span>Coinbase</span><i>→</i><span>Kafka</span><i>→</i><span>Spark</span><i>→</i><span>Postgres</span></div></div></div><span className="stream-stamp">10K+ <small>EVENTS / MIN</small></span></div>
  return <div className="project-art charts-art" aria-hidden="true"><div className="chart-input"><div className="chart-input-header">01 / SEE THE DATA <span>▥</span></div><div className="mini-bar-chart">{[36, 61, 47, 78, 66, 91].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div><span className="chart-axis">CHART IMAGE →</span></div><span className="chart-connector">✳</span><div className="chart-output"><div className="chart-output-header"><span>✧</span> THE BIG PICTURE</div><div><span className="insight-dot" /><p><strong>Summary</strong><span>The story behind the numbers.</span></p></div><div><span className="insight-dot" /><p><strong>Trends & patterns</strong><span>See what’s changing over time.</span></p></div><div><span className="insight-dot" /><p><strong>Unexpected findings</strong><span>A little context goes a long way.</span></p></div></div><span className="visual-note">a new perspective on your data ✧</span></div>
}

export default function Projects() {
  const [selected, setSelected] = useState<number | null>(null)
  const dialog = useRef<HTMLDialogElement>(null)
  const previousFocus = useRef<HTMLElement | null>(null)
  useEffect(() => {
    const element = dialog.current
    if (selected === null || !element) return
    previousFocus.current = document.activeElement as HTMLElement
    element.showModal()
    const previousOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    return () => { element.close(); document.body.style.overflow = previousOverflow; previousFocus.current?.focus() }
  }, [selected])
  const project = selected === null ? null : projects[selected]
  return <section className="work-section section-pad" id="work"><div className="content-width">
    <div className="section-kicker"><span>02 / A FEW THINGS I’VE BUILT</span><span>IDEAS → REALITY</span></div>
    <div className="section-heading" data-reveal><h2>Serious problems.<br /><span className="serif">Thoughtful solutions.</span></h2><p>A selection of projects where curiosity<br />met code—and something clicked.</p></div>
    <div className="project-list">{projects.map((item, index) => <article className={`project-card project-${item.id}`} key={item.id} data-reveal><ProjectVisual id={item.id} /><div className="project-content"><div className="project-meta"><span>{item.category}</span><span>/{item.number}</span></div><h3>{item.name}</h3><p className="project-subtitle">{item.subtitle}</p><p className="project-description">{item.description}</p><div className="project-tags">{item.tech.map(tech => <span key={tech}>{tech}</span>)}</div><div className="project-footer"><div className="project-metric"><strong>{item.metric}</strong><span>{item.metricLabel}</span></div><button className="project-open" onClick={() => setSelected(index)} aria-label={`Explore ${item.name}`}><FiArrowUpRight /></button></div></div></article>)}</div>
    <a className="github-link" href="https://github.com/tanyamistry" target="_blank" rel="noreferrer"><FiGithub /><span>There’s more where that came from.</span><strong>Find me on GitHub <FiArrowUpRight /></strong></a>
  </div>
  <dialog className="project-dialog" ref={dialog} onCancel={() => setSelected(null)} onClick={event => { if (event.target === event.currentTarget) setSelected(null) }} aria-labelledby="project-dialog-title">
    {project && <div className="dialog-inner"><div className="dialog-top"><span className="mono">UNDER THE HOOD / {project.number}</span><button onClick={() => setSelected(null)} aria-label="Close project details" autoFocus><FiX /></button></div><h2 id="project-dialog-title">{project.name}</h2><p className="dialog-subtitle">{project.subtitle}</p><ul>{project.details.map(detail => <li key={detail}>{detail}</li>)}</ul><div className="project-tags">{project.tech.map(tech => <span key={tech}>{tech}</span>)}</div><a className="button button-lime" href={project.url} target="_blank" rel="noreferrer"><FiGithub /> Explore the code <FiArrowUpRight /></a></div>}
  </dialog>
  </section>
}
